name: Create release tag
on: 
  workflow_dispatch:
    inputs:
      development-version:
        description: 'Version to set in development branch'     
        required: true
      release-version:
        description: 'Version to create/release'
        required: true

env:
  GITHUB_TOKEN: ${{ secrets.PAT }}

jobs:
  create-tag:
    runs-on: ubuntu-latest
    env:
      DEVEL_VERSION: ${{ inputs.development-version }}
      RELEASE_VERSION: ${{ inputs.release-version }}
    steps:
      - name: Show versions
        run: |
          echo "Development : $DEVEL_VERSION"
          echo "Release : $RELEASE_VERSION"
      - uses: actions/checkout@v3
        with:
          token: ${{ env.GITHUB_TOKEN }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Init Git info
        run: |
          git config --global user.email "actions@workflow.github.com"
          git config --global user.name "GitHub Actions"
      - name: Release
        run: "mvn -B -DlocalCheckout=true -DscmCommentPrefix=\":bookmark: \" release:prepare -DreleaseVersion=$RELEASE_VERSION -DdevelopmentVersion=$DEVEL_VERSION -DtagNameFormat=\"@{project.version}\""
