name: Create and publish release from tag

on:
  push:
    tags:
      - "*"
env:
  MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PAT }}
  MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
jobs:
  release-create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} 
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Deploy on ossrh
        run: mvn -Prelease -B clean deploy -DskipTests
      - name: Create GitHub Release
        uses: fregante/release-with-changelog@v3
        with:
          tag: $RELEASE_VERSION
          token: ${{ secrets.GITHUB_TOKEN }}
